version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 24:fe:5c:41:f2:da:6d:5a:5c:5d:d4:76:6b:d0:7d:e8
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
        
      - run:
          name: Run Tests in docker
          command: |
            . helloworld/bin/activate
            
    
      - run:
          name: Build and push Docker image to docker registry test
          command: |
            . helloworld/bin/activate     
           
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |
            ssh -v git@github.com
            ssh -v dasndasdone@34.68.161.68
            ssh -o StrictHostKeyChecking=no 34.68.161.68 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"      
              
           
