version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 8f:af:44:64:14:2f:b1:bc:3b:03:ba:d4:0a:b4:a6:f7
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
        
      - run:
          name: Run Tests in docker
          command: |
            . helloworld/bin/activate
            
    
      - run:
          name: Build and push Docker image to docker registry test
          command: |
            . helloworld/bin/activate     
           
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |            
            ls
            ssh -v  34.68.161.68
            ssh -o StrictHostKeyChecking=no 34.68.161.68 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"      
              
           
