version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - d4:f9:83:ad:c7:cf:31:d7:54:0d:13:8b:9d:36:16:cc
      - run:
          name: Setup Virtual Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
        
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            
     // - setup_remote_docker:
        //  docker_layer_caching: false //--true
      - run:
          name: Build and push Docker image to docker registry test
          command: |
            . helloworld/bin/activate     
           
      - run:
          name: Deploy app to Linode Producrion Server via Docker
          command: |
            ssh -v git@github.com
            ssh -v dasndasdone@34.68.161.68
            ssh -o StrictHostKeyChecking=no 34.68.161.68 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"      
              
           
